### ISSUE TITLE
Runahead broken with Tengai Makyou Zero?

### ISSUE THREAD

**Issue by SimpleTease** [libretro/snes9x#109]
Hi, trying to use runahead latency option at 1 frame (second core both on/off) but seems to behave badly with this game. Screen will randomly freeze but game will continue normally (sounds, cutscenes, button pushes). Not sure if this is fixable but it's a great invention. Thanks!

**Comment by kps501** [comment]
It was interlace loadstate issue in snes9x core - not dwedit fault. Runahead works with latest build. No problems found with TMZ. This issue can probably be closed.
