### ISSUE TITLE
Randomize ram on game startup?

### ISSUE THREAD

**Issue by SimpleTease** [libretro/snes9x#110]
Hi, can there be feature to randomize memory when on bootup? Some games like Super Off Road are known to use uninitialized ram as a seed for random number generator. This controls bonus placements, ai nitro behavior, and some other things -- makes game more unpredictable. iirc other games do this for random weather behavior or showing random characters on splash screens. Thanks!

**Comment by kps501** [comment]
I added a randomizer flag inside snes9x libretro file:
static void update_variables(void)

It works but this setting doesn't seem to save when Retroarch closes (always default disabled on emu start). Does anyone know why this happens? I'd also like to try adding M.A.C.S. Rifle support sometime later.

**Comment by kps501** [comment]
PR pushed. Will wait for nightly buildbot to finish and retest, before asking for closing.

Note that snes9x devs mention this feature can produce unstable results. Even higan selectively does pseudo-random memory so it is troublesome feature to correctly emulate.

**Comment by kps501** [comment]
memmove error. It's fixed in latest nightly - no more flicker. I'm done here.
https://buildbot.libretro.com/nightly/

**Comment by stellarporter** [comment]
libretro has the randomizer option. Super Off Road demos show different stuff at every clean bootup. Some other demos show same behavior.
