### ISSUE TITLE
Black screen at start with crop overscan not on auto and runahead enabled

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/snes9x#134]
@kps501

After recent commits I got a black screen (most of the time, can be random), game is still running with sound in the background, if I have core option "Preferred Aspect Ratio" on "auto".

Log shows:
```
[INFO] SET_GEOMETRY: 256x224, aspect: 1.#IO.
```
It seems fine on other ratio values.

Win7 x64, Nvidia GTX770, current Retroarch Nightly, snes9x e9f5178539ebc0567ddbb64335e7164d9f58de6b and ac4b54c18ff0f9ee7b5144b97068cee347ad5ef5

**Comment by kps501** [comment]
Oh crap. I'll re-diff check everything with upstream and look for answers.

**Comment by kps501** [comment]
To make sure I'm not going crazy, please try clean stable Retroarch 1.7.3 release first.
http://retroarch.com/?page=platforms

I'm not sure how 'auto' (0) works, looking at snes9x libretro code.

**Comment by Tatsuya79** [comment]
I just know 4d9f365bb672e691f749beb8a9f8e8388b563b01 is fine here, I'll do more tests...

**Comment by Tatsuya79** [comment]
If ratio option is on auto, aspect_ratio_mode = 0 and the code go there:
https://github.com/libretro/snes9x/blob/master/libretro/libretro.cpp#L388

**Comment by Tatsuya79** [comment]
Mmm I can't reproduce it with run_ahead to OFF so it probably has to do with that feature.

**Comment by kps501** [comment]
Okay, all above notes definitely help. I know snes9x devs did some interlace fixes involving fast-forward. And maybe few other things. I'll look more carefully until someone finds an answer. Maybe some libretro lines got blown up by mistake. :|

**Comment by twinaphex** [comment]
How severe is this issue right now? How long is it going to take to track this down?

Maybe we should just revert everything until you can handtest everything and make sure there are no regressions along the way.

**Comment by kps501** [comment]
Because I can't trigger this error, I'm okay with reverting everything. I'd say it's going to take awhile unless Tatsuya79 can find a specific spot.

**Comment by Tatsuya79** [comment]
If it's only caused by run_ahead and a problem between the core instances perhaps @Dwedit will understand it better?

**Comment by kps501** [comment]
You're right - I can trigger it with overscan crop also. Wonder why...??

**Comment by Tatsuya79** [comment]
Even without using run_ahead you did reproduce it?

**Comment by kps501** [comment]
Weirdly, I'm locked out of my account for awhile. o_O If someone else wants to pr in the meantime, you just need to edit this:

libretro\libretro.cpp @ static void update_variables(void) @ ~line 323
	// hack: multi-instance runahead cores
   //if (geometry_update)
     update_geometry();


That's it! Maybe dwedit can find a better way to handle this.

**Comment by Tatsuya79** [comment]
I could reproduce the issue (run ahead + overscan ON = black screen, wrong ratio in log) on a version without your changes so we brought the commits back, sorry about that!
This bug is a bit random and I didn't notice it before, but it was there.

**Comment by retro-wertz** [comment]
seems like more of a runahead issue not able to pass when RETRO_ENVIRONMENT_SET_GEOMETRY is called, something similar to what happens in fceumm.

**Comment by kps501** [comment]
Found it. When retro_load_game is called, update_geometry after rom is fully loaded - ntsc vs pal, misc timings.

**Comment by retro-wertz** [comment]
not sure how that can be missed. probably this one? **SNES::cpu.frequency** in get_aspect_ratio() ( i honestly dont quite understand class structure thing...)
anyways its probably better to force geometry update in check_variables similar to fceumm or probably just force call it in retro_run at least once after 1st loop or so...

JMHO.

**Comment by kps501** [comment]
before:
bool retro_load_game(const struct retro_game_info *game)
{
   init_descriptors();
   memorydesc_c = 0;

   // too early for Retroarch -- set up geometry and misc
   update_variables();

   if(game->data == NULL && game->size == 0 && game->path != NULL)
      rom_loaded = Memory.LoadROM(game->path);
   else
   {
      if (game->path != NULL)
      {
         extract_basename(g_basename,   game->path, sizeof(g_basename));
         extract_directory(g_rom_dir, game->path, sizeof(g_rom_dir));
      }

      rom_loaded = Memory.LoadROMMem((const uint8_t*)game->data ,game->size);
   }

   int pixel_format = RGB555;
   if(environ_cb) {
      pixel_format = RGB565;
      enum retro_pixel_format fmt = RETRO_PIXEL_FORMAT_RGB565;
      if (!environ_cb(RETRO_ENVIRONMENT_SET_PIXEL_FORMAT, &fmt))
         pixel_format = RGB555;
   }
   S9xGraphicsDeinit();
   S9xSetRenderPixelFormat(pixel_format);
   S9xGraphicsInit();

   if (!rom_loaded && log_cb)
      log_cb(RETRO_LOG_ERROR, "[libretro]: Rom loading failed...\n");

   /* Check if Chrono Trigger is loaded, if so, we need to set a variable to
    * true to get rid of an annoying mid-frame resolution switch to 256x239
    * which can cause an undesirable flicker/breakup of the screen for a
    * split second - this happens whenever the game switches from normal
    * mode to battle mode and vice versa. */
   ChronoTriggerFrameHack = false;
   if (Memory.match_nc("CHRONO TRIGGER") ||	/* Chrono Trigger */
      Memory.match_id("ACT") ||
      Memory.match_id("AC9J")		/* Chrono Trigger (Sample) */
      )
         ChronoTriggerFrameHack = true;

   struct retro_memory_map map={ memorydesc+MAX_MAPS-memorydesc_c, memorydesc_c };
   if (rom_loaded) environ_cb(RETRO_ENVIRONMENT_SET_MEMORY_MAPS, &map);

   return rom_loaded;
}


after:
bool retro_load_game(const struct retro_game_info *game)
{
   init_descriptors();
   memorydesc_c = 0;

   if(game->data == NULL && game->size == 0 && game->path != NULL)
      rom_loaded = Memory.LoadROM(game->path);
   else
   {
      if (game->path != NULL)
      {
         extract_basename(g_basename,   game->path, sizeof(g_basename));
         extract_directory(g_rom_dir, game->path, sizeof(g_rom_dir));
      }

      rom_loaded = Memory.LoadROMMem((const uint8_t*)game->data ,game->size);
   }

   int pixel_format = RGB555;
   if(environ_cb) {
      pixel_format = RGB565;
      enum retro_pixel_format fmt = RETRO_PIXEL_FORMAT_RGB565;
      if (!environ_cb(RETRO_ENVIRONMENT_SET_PIXEL_FORMAT, &fmt))
         pixel_format = RGB555;
   }
   S9xGraphicsDeinit();
   S9xSetRenderPixelFormat(pixel_format);
   S9xGraphicsInit();

   if (!rom_loaded && log_cb)
      log_cb(RETRO_LOG_ERROR, "[libretro]: Rom loading failed...\n");

   /* Check if Chrono Trigger is loaded, if so, we need to set a variable to
    * true to get rid of an annoying mid-frame resolution switch to 256x239
    * which can cause an undesirable flicker/breakup of the screen for a
    * split second - this happens whenever the game switches from normal
    * mode to battle mode and vice versa. */
   ChronoTriggerFrameHack = false;
   if (Memory.match_nc("CHRONO TRIGGER") ||	/* Chrono Trigger */
      Memory.match_id("ACT") ||
      Memory.match_id("AC9J")		/* Chrono Trigger (Sample) */
      )
         ChronoTriggerFrameHack = true;

   struct retro_memory_map map={ memorydesc+MAX_MAPS-memorydesc_c, memorydesc_c };
   if (rom_loaded) environ_cb(RETRO_ENVIRONMENT_SET_MEMORY_MAPS, &map);

   // this reads retroarch variables and sets up geometry + misc
   update_variables();

   return rom_loaded;
}

**Comment by Tatsuya79** [comment]
It seems to work for most games but Yoshi's Island is always giving me a black screen/freeze/crash RA on overscan option change.

**Comment by kps501** [comment]
Found out that we *must* do update variables first, otherwise some settings won't work. Which goofs up crop again. So using force geometry hack again. And looking more into retro_wertz solution.

**Comment by retro-wertz** [comment]
sent PR

not sure if overclock was suppose to work on-the-fly, but at least Yoshi's Island does not work when S9xResetSuperFX() is called after game has already loaded.

**Comment by kps501** [comment]
That's actually interesting. Admittedly I don't know how SuperFX overclock works, other than 1.56 handles somewhat differently lately. I'll look into this upstream.

Maybe we could do this, like you suggest:

retro_load_game
update_variables - read retroarch stuff 1st
Memory.loadrom - this does all important snes boot stuff: ram reset, rom detection, ppu reset, gfx start, blah blah
update_geometry - since we now know timings, pal, overscan, and core is setup: force it again (good idea!)

This seems to work (so far). I'll change my PR which I think doesn't conflict with yours or Dwedit's.

**Comment by Tatsuya79** [comment]
Looks fine now, thanks!
