### ISSUE TITLE
Cannot run roms in libretro version.

### ISSUE THREAD

**Issue by ElementalWarrior** [libretro/snes9x#14]
I just compiled the libretro version of snes9x for the rpi. 

Tried to start Super Bomberman 2 and it just tells me my joystick loaded at the bottom of the screen, then halts at a black screen. No audio.

```
/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-snes9x/libretro.so ~/RetroPie/roms/snes/Super\ Bomberman\ 2\ \(USA\).zip


Sound buffer size: 2048 (512 samples)
RetroArch [WARN] :: patch_content :: Did not find a valid content patch.
Map_HiROMMap
RetroArch [WARN] :: gl_glsl_init :: [GL]: Stock GLSL shaders will be used.
```

Thoughts?

**Comment by Kivutar** [comment]
I can reproduce this on OdroidXU3. It may be a bug that affects all Linux ARM?

Black screen, no audio.

**Comment by AlexMax** [comment]
I'm actually having this precise issue (black screen, no audio) with the buildbot-provided armhf nightly build of snes9x.

snes9x_next works just fine, so that's what I'm using for now.

**Comment by meepingsnesroms** [comment]
Is this still an issue?

**Comment by ElementalWarrior** [comment]
Couldn't tell you. Haven't tried since. I don't think I ever got it working.

**Comment by fr500** [comment]
This issue was moved to libretro/libretro-meta#7
