### ISSUE TITLE
libretro port - feature creep list?

### ISSUE THREAD

**Issue by kps501** [libretro/snes9x#154]
Just a suggestion list: todo stuff or reasonable features. Nothing may get done but just compiling.

If games are broken, please check upstream first and report there.
https://github.com/snes9xgit/snes9x/issues
(if they can't fix it upstream for a long while, then try requesting hack in this thread)

                       ## upstream backport ##
Dragon Ball Z: Super Butouden 2 (Rev1) <-- experimental fix, waiting

                         ## libretro port ##
investigate bit-perfect dsp opcodes <-- check upstream dsp3,dsp4,st010
check selective hires game blending <-- JP, KDL3, SM-Kondo

                       ## libretro game hacks ##
Soul Blazer - slow intro music tempo <-- heard this happens sometimes due to apu timing, needs investigating up/down stream
Stunt Race FX - menu flicker <-- unsure, devs think this is problematic so far

**Comment by kps501** [comment]
Question: upstream 1.56 does SuperFX clocking as percentage. This is actually applied in real-time and automatically takes into account clock divider (10 vs 20). No need to call S9xResetSuperFX, which might goof irqs and registers.

Should we keep 10,20,40,60,80,100MHz or switch to new 50,100,200,300,400,500% formula?

**Comment by hizzlekizzle** [comment]
I vote for percent. We typically want to match upstream when possible, and it sounds like it has some advantages over the stepped method anyway.

**Comment by meepingsnesroms** [comment]
I vote percent as well, its easier for end users to understand.

**Comment by kps501** [comment]
Okay, so we got a lot done and now caught up with upstream. Is there anything else somewhat useful or interesting to add to list (within possibility)? Adding audio interpolation was not on the list but unexpectedly, decently easy to do. ^^

AFAIK, nearly everything I personally wanted is done.

**Comment by kps501** [comment]
My own build with more custom junk.
https://github.com/kps501/bright_snes9x
