### ISSUE TITLE
Request for Core Option to toggle On/Off Use of BS-X/Sufami Turbo BIOSES

### ISSUE THREAD

**Issue by KMFDManic** [libretro/snes9x#164]
Truly exceptional work on the direct loading of BS-X and Sufami Turbo Games!  I released the latest Commits for users on SNES/NES Classic Systems.  There are a couple minor conflicts.  One:  If BIOS for BS-X are not present on a game that wants to use them, the game fails to load.  Having a toggle ability so they are completely ignored will be there for those who do not want to run the BS-X BIOS.  Two:  This conflict does not apply to PC/RetroPie/Other Formats.  It is entirely specific to the SNES Classic.  SNES Games are converted into a special .Sfrom format that run natively with the default Emulator that comes with the SNES Classic (Canoe Emulator).  If BIOS for BS-X are being used, .Sfroms will not work.  If BIOS for BS-X are not used, .Sfroms do work.  So, this is another thing that is incredibly helpful for those who do not want to use workarounds to bypass the .Sfrom Conversion, and maintain the original .sfc, etc formats.  Thanks so much for reading.  Hope this can be implemented as a Core Option, as it will ensure those who want to use them and those who do not want to use them will both be happy:)

**Comment by KMFDManic** [comment]
@kps501 @Tatsuya79  I would also like to note, patching the BS-X BIOS with the English+DRM Patch, greatly increases compatibility.  Nearly every game worked for me, once patched.  Plus, the obviously nicety of being in English:)  Just a few had title screens which couldn't be bypassed (these games can be patched, as well).  Thanks again for this really cool "Authentic" Experience Gimmick:)  And, much appreciated, if a Core Option can be done!

**Comment by kps501** [comment]
I think it's possible but you'd have to wait for the 1.56 rebase, which will slim down options and refocus the experience.

If you don't want to wait, fork the project. I'll try sending a pr and you can release your own version until the future comes.

**Comment by KMFDManic** [comment]
@kps501 That is incredibly awesome of you to do this:)  I forked it to:

https://github.com/KMFDManic/snes9x

This will go a tremendous way, as far as contending with .Sfroms and those who would prefer BIOS be optional.  I will personally keep using them, as I love the Gimmick of the Town With No Name:)  Thanks again!
