### ISSUE TITLE
Secret of Evermore - wrong tiles

### ISSUE THREAD

**Issue by Papermanzero** [libretro/snes9x#177]
Play secret of evermore, after sometime you recognize in some sprites wrong tiles. Just enter and leave one area/room until an unexpected tile occurs. This issue is easily reproducible witch the PAL version.
Retroarch Win Version (Win10)
GPU Nvidia GTX 760

![secret of evermore-180827-090203](https://user-images.githubusercontent.com/10263536/44645499-1844eb00-a9d8-11e8-9663-8b28ed700b30.png)

**Comment by hizzlekizzle** [comment]
Can you see if the same thing happens with snes9x standalone?

**Comment by Papermanzero** [comment]
I can try

**Comment by ramtrooper** [comment]
devs now create libretro dlls via appveyor
https://ci.appveyor.com/project/snes9x/snes9x/build/1.56.2-380


Select one of the libretro builds and click artifacts tab. If error still happens, go complain up there. Chances are they'll find a fix.

**Comment by fr500** [comment]
the libretro buildbot core is by all means identical to upstream.

**Comment by Papermanzero** [comment]
Tested the appvoyer build, and this one fixes the issue.
Consequently the snes9x version which is hosted via the libretro update service and which is available in this repository contains the issue.

So somehow the libretro version has to stay at the latest build by either mirroring the snes9x repository 1:1 or via using the build from appveyor.

**Comment by fr500** [comment]
The core is 1:1 already there are no differences other than being 47
commits behind.

That could be it.

Their builds are made with msvc that could be too.

**Comment by Papermanzero** [comment]
For sure the core is the same however the version/ commit is not :-)

The snes9x team inteoduced several optimisations in the last commits which are missing in this repository

**Comment by OV2** [comment]
We can kill the libretro/msvc folder - I think that came over when importing changes. However I'd like to keep the libretro-win32.vcxproj file, since I use that for debugging and it's used in the appveyor build. If you don't want it visible in the libretro folder we can probably move it somewhere else though.

**Comment by retrotalker** [comment]
I can adjust the current master appveyor script to add libretro uwp platforms. For libretro desktop releases, both sides can decide which default version to use or include all of them. No preference on my end.

1. win32 release - x86,x64
2. libretro release vcxproj - x86,x64 <--> libretro make - desktop x86,x64
3. libretro make - uwp x86,x64,arm
