### ISSUE TITLE
(Bounty) Enable Blargg NTSC Filters Core Option

### ISSUE THREAD

**Issue by mr-falafel** [libretro/snes9x#186]
It is my understanding that this core has/had a built-in core option for Blargg's NTSC Filters but that it is currently disabled. Would it be possible to enable it again?

edit: I have put a $15 bounty on this issue, via Bountysource.

**Comment by mr-falafel** [comment]
I'd like to add a bounty for this on Bountysource but I can't find it on there. Once I can, I will. I'm afraid this is all quite new to me. Haha

**Comment by stellarporter** [comment]
Added blargg filter to libretro port. Ready for PR into libretro/snes9x.
https://github.com/stellarporter/snes9x/tree/blargg

**Comment by mr-falafel** [comment]
Awesome! Thank you so much!

**Comment by mr-falafel** [comment]
How long should it take for this to merge over?

**Comment by hizzlekizzle** [comment]
Should be closed by https://github.com/libretro/snes9x/pull/206.

With this issue closed, the bounty can be marked as solved and the donors can approve the solution.

**Comment by mr-falafel** [comment]
Core option is there but the filters are crazy broken! Guess that's why they were disabled...?

**Comment by stellarporter** [comment]
Which OS and game? Tested latest git https://github.com/libretro/snes9x/commit/7103f840a15f01a7dc63ae9fb9b4a9261e5e1b14 on Windows. Tried all filters with shaders and nothing awful happened yet on several games: Donkey Kong Country, Super Metroid, Seiken Densetsu 3, Jurassic Park, Zelda Link to Past, Super Mario World.

**Comment by hizzlekizzle** [comment]
I'm getting in linux x86_64, as well:
![Screenshot from 2019-03-20 17-56-19](https://user-images.githubusercontent.com/2805586/54725873-a46a5b80-4b3e-11e9-85c0-bb3817b67b12.png)

**Comment by stellarporter** [comment]
Changed browser and now I can the KDL3 and 240p screenshot. That heavy green tint suggests a 555 - 565 conversion error somewhere. Why I'm mysteriously not affected is (..?)

I'll give everything another lookover and see if I can bash something out of this.

**Comment by retro-wertz** [comment]
![Screenshot from 2019-03-21 08-48-33](https://user-images.githubusercontent.com/23315382/54728055-5c871b00-4bb6-11e9-8d98-b8a35c671426.png)

this is why i believe that extra options (sound filters, gfx shaders etc ) if possible should be done in frontend through shaders etc unless they are part of original hardware or emulates what the hardware actually do or have. imho

**Comment by stellarporter** [comment]
Supposedly some Retroarch ports don't support gpu shaders? Thought I remember someone request a crop feature for C64 VICE core, like how the NES ones do it.

I'm personally neutral on this subject though and willing to fall on either end of the blade. Guidance from thread author and repo owners?

**Comment by twinaphex** [comment]
I think the blargg NTSC filters added could definitely have value, so yeah, I don't have anything inherently against them.

If you have a new PR where the graphical output issues are fixed with blargg NTSC and we can make Emscripten work, then we can merge it without any issues as far as as I"m concerned.

**Comment by stellarporter** [comment]
I think the problem could be this line:
https://github.com/libretro/snes9x/blob/master/filter/snes_ntsc_config.h#L6

Threw these into each code path and compiler says 565 (win32).
```#pragma message ("blargg 555")```
```#pragma message ("blargg 565")```

I expect nearly all ports to be 565 libretro output, but my assumption is blargg library incorrectly compiles with 555 math which whacks out the colors. Could someone test this theory?

If above is true, libretro uses this flag to test for 565 but I'm unsure how to push this into filter/snes_ntsc_config.h
https://github.com/libretro/snes9x/blob/master/libretro/libretro.cpp#L994

**Comment by stellarporter** [comment]
Going to try changing ```#if !defined(SNES9X_GTK) && !defined(_WIN32)``` to ```#if PIXEL_FORMAT == RGB555```.

**Comment by mr-falafel** [comment]
> ![Screenshot from 2019-03-21 08-48-33](https://user-images.githubusercontent.com/23315382/54728055-5c871b00-4bb6-11e9-8d98-b8a35c671426.png)
> 
> i believe that extra options (sound filters, gfx shaders etc ) if possible should be done in frontend through shaders etc unless they are part of original hardware or emulates what the hardware actually do or have or are actually unique. imho

My understanding is that the blargg filters are specifically tailored for each console. I understand that this is somewhat a personal preference but I feel like the emulation is incomplete without the video processing of the original hardware. Unfortunately, Retroarch's blargg video filters don't work very well for me, here in linux land. The filters built in to other emulators, such as Mesen, work perfectly. This is the reason for my request.

**Comment by mr-falafel** [comment]
Option for Blargg filters is in snes9x now gone again, for me. Is that right?

**Comment by hizzlekizzle** [comment]
Yes, we reverted it while we look for a good solution to the pixel format issue.

**Comment by mr-falafel** [comment]
Okay, that makes sense! Sorry for not properly understanding the thread.

**Comment by mr-falafel** [comment]
Do you think I should start a new issue for the filters being broken on linux?

**Comment by hizzlekizzle** [comment]
No, I think this is fine. We'll just reopen this one temporarily so it doesn't get lost/forgotten.

**Comment by mr-falafel** [comment]
That's great, thanks. :)

**Comment by stellarporter** [comment]
@mr-falafel 
Tried compiling some binaries for linux. Have no idea if they work but if you're feeling experimental, ideally they should be master git + blargg filter pr.
https://ci.appveyor.com/project/stellarporter/snes9x/builds/23436553

**Comment by mr-falafel** [comment]
Working beautifully for me!
![kirby_ntsc](https://user-images.githubusercontent.com/43884729/55222714-7d79ec80-5204-11e9-9c54-33eb276549d1.png)

**Comment by mr-falafel** [comment]
Though, I have only tested the 64bit build. I'm on 64bit Linux Mint.

**Comment by stellarporter** [comment]
Cool. So we know is doing something right.
https://github.com/libretro/snes9x/pull/207

appveyor.yml build script
```
version: 0.1.{build}

shallow_clone: true

image:
- ubuntu1804

before_build:
  - sudo apt-get --assume-yes install gcc-multilib g++-multilib

build_script:
  - gcc -v
  - cd libretro
  
  - make -f Makefile platform=unix CFLAGS='-m32' CXXFLAGS='-m32' LDFLAGS='-m32'
  - mkdir lib32
  - mv snes9x*.so lib32
  - make clean
  
  - make -f Makefile platform=unix
  - mkdir lib64
  - mv snes9x*.so lib64
  
artifacts:
  - path: '**\snes9x*.so'
```

**Comment by mr-falafel** [comment]
As soon as this gets merged, I'd be very happy for the bounty to be claimed!

**Comment by mr-falafel** [comment]
Is it just a matter of waiting, now?

**Comment by hizzlekizzle** [comment]
Is it in the buildbot builds now? Are all platforms building and functioning with proper colors?

**Comment by mr-falafel** [comment]
The latest nightly build for windows and linux is from the 22nd of last month. I'm assuming nightly is where I should be looking. I don't know about other platforms but this build still has the filters disabled for linux because they were broken. Stellarporter's fix worked perfectly for me so I'm just waiting for it to go into the buildbot before I mark this as solved.

**Comment by mr-falafel** [comment]
I can see that there's a new build of snes9x in the buildbot, today. However, upon testing it, the blargg filter option is still hidden.

**Comment by mr-falafel** [comment]
Still no linux build with the filters enabled. I can see that the fix has been applied (I think) in the commits but I think they still need to be re-enabled, on the linux build. Meaning the option to turn them on is missing from the core options, right now.

**Comment by hizzlekizzle** [comment]
This should be fixed now. I'm going to close it so @stellarporter can claim the bounty.

**Comment by mr-falafel** [comment]
Fantastic! I'd be very happy for @stellarporter to claim the bounty, now. :)
