### ISSUE TITLE
Libretro update version 1.56.2 to the official version 1.57

### ISSUE THREAD

**Issue by ToniBC** [libretro/snes9x#190]
It has been a while since the official Snes9x version was updated at 1.57 with several fixes but the version of Libretro remains at 1.56.2. Apparently it is already updated, but not compiled, since the last compilation was on 10-28-2018.

**Comment by hizzlekizzle** [comment]
Hmm, yeah, looks like it's been failing to build for a while:
http://p.0bl.net/66899

**Comment by bearoso** [comment]
Sorry about that. If you merge the latest snes9xgit tree it's fixed, and there's also another fix for interlaced modes.
