### ISSUE TITLE
Axelay graphic problems

### ISSUE THREAD

**Issue by ToniBC** [libretro/snes9x#204]
In the game Axelay presents a small graphic error in the upper part that could be present in other games. Above the photo you can see a gradient of the sky and then you see the background of the phase, but it is incorrect, it is missing as a white fade between the two as if Bsnes v107 and other versions.

Incorrect image, white gradient is missing and cut as objects.
![falla](https://user-images.githubusercontent.com/45365478/53881874-1017d900-4015-11e9-932f-2c01269d0658.png)

In Bsnes v107 or earlier, the image looks correct.
![correcta](https://user-images.githubusercontent.com/45365478/53881936-39386980-4015-11e9-9a4d-d57ea03e39c0.png)

**Comment by Tatsuya79** [comment]
This got fixed upstream.

**Comment by stellarporter** [comment]
Haven't tested this game but I see this libretro commit, which should fix the brightness blending problem
https://github.com/libretro/snes9x/commit/db8227fa428b865cdc238764d56ebd4d6d42464e

**Comment by ToniBC** [comment]
It seems that they fixed the problem, so I close the issue.

Thank you so much.
