### ISSUE TITLE
last update of snes9x android msu-1 broken

### ISSUE THREAD

**Issue by srk15372** [libretro/snes9x#211]
Hi, I have just update the core on android shield tv and now,
all msu-1 roms are broken, the screen is completely distorded.
hope you could restore this feature on android  thanks

**Comment by hizzlekizzle** [comment]
I don't think this has anything to do with MSU1. Can you test some non-MSU1 games?

**Comment by srk15372** [comment]
You are right, I test a snes rom and it doesn t launch correctly, the screen is completely distorted.
So I delete the core, delete save, state, option in core option file, update retroarch, redownload the core but no luck. All others core works fine. Is someone could test on android the last core to see if there is a problem? thanks for your support

**Comment by srk15372** [comment]
And I test on retroarch 64 bits edition and it works, but no luck with 32 bits retroarch version

**Comment by srk15372** [comment]
so I test a former snes9x core about a backup I made and remplace it (my shield tv is rooted with the access to the cores folder): and it's works.
So I think the last revision is broken on android

**Comment by hizzlekizzle** [comment]
I'm going to close this issue in favor of this other one that's describing the same issue but has a screenshot and a better title/explanation (i.e., no MSU1 red herring):
https://github.com/libretro/snes9x/issues/212
