### ISSUE TITLE
Blargg NTSC filters are completely broken on Android

### ISSUE THREAD

**Issue by turboboy215** [libretro/snes9x#214]
When I try running any game with a filter, the screen looks absolutely hideous with a mixture of green and blue colors, the same effect in the picture below that someone posted a while ago but was supposedly fixed.
![54725873-a46a5b80-4b3e-11e9-85c0-bb3817b67b12](https://user-images.githubusercontent.com/15841765/57999113-11d83100-7a89-11e9-902c-6f10b3d28c5e.png)

When I try using the PC version, it works fine. Why is this happening to me? Is this some color conversion issue that never got fixed on Android?

**Comment by hizzlekizzle** [comment]
It probably came back with this commit: https://github.com/libretro/snes9x/commit/52f521160a3fed88dcbf8050e41b3c4078fb04d4

Without that commit, the image is broken all the time (wrong pitch). This has been a frustrating whack-a-mole problem...

**Comment by funbars** [comment]
Please try this
https://ci.appveyor.com/project/funbars/snes9x/builds/24824162/artifacts

libretro/jni/Android.mk:
```
LOCAL_PATH := $(call my-dir)

CORE_DIR := $(LOCAL_PATH)/../..

include $(CORE_DIR)/libretro/Makefile.common

COREFLAGS := -DANDROID -D__LIBRETRO__ -DHAVE_STRINGS_H -DRIGHTSHIFT_IS_SAR $(INCFLAGS)

GIT_VERSION := " $(shell git rev-parse --short HEAD || echo unknown)"
ifneq ($(GIT_VERSION)," unknown")
  COREFLAGS += -DGIT_VERSION=\"$(GIT_VERSION)\"
endif

include $(CLEAR_VARS)
LOCAL_MODULE    := retro
LOCAL_SRC_FILES := $(SOURCES_C) $(SOURCES_CXX)
LOCAL_CXXFLAGS  := $(COREFLAGS)
LOCAL_CFLAGS    := $(COREFLAGS)
LOCAL_LDFLAGS   := -Wl,-version-script=$(CORE_DIR)/libretro/link.T
include $(BUILD_SHARED_LIBRARY)
```

**Comment by turboboy215** [comment]
How do I use this code? It looks like it most likely fixes the problem, but I don't know how to use this AppVeyor website to compile the code to a core.

**Comment by funbars** [comment]
Appveyor built Android cores at link above. Select *.so core for your Android and play.

**Comment by turboboy215** [comment]
I can load the .so file into RetroArch, but there's no updated info on it, and I can't load ROMs with the core since they aren't associated with it. What do I do? I tried doing the "Core updater" with no success. It still won't let me open ROMs with it, as it just shows the list of other SNES cores.

**Comment by hizzlekizzle** [comment]
you should be able to load core > pick it from the list even with its raw lib name > load content

**Comment by turboboy215** [comment]
I tried that now, but it now says "Failed to load content." and then goes to a screen with no core and no items. What am I doing wrong?

**Comment by turboboy215** [comment]
It still won't show up, even with the raw name libretro.so. When I load the core, it doesn't give me the option for core info like the others, and it won't show up in the list of selected cores after I add the core. Is there something I need to update, like a missing configuration file?

**Comment by funbars** [comment]
Other than rename "snes9x_libretro_android.so", no idea. Maybe core in wrong folder?

Submitted fix upstream, since makefile is wrong.

**Comment by turboboy215** [comment]
Yes! Renaming the core file worked! Thank you! And that problem was fixed, so now I can play SNES games with the effect! Feel free to close this issue now.

**Comment by hizzlekizzle** [comment]
Yes, Appveyor build works here, even with the NTSC filter enabled. Thanks @funbars!
