### ISSUE TITLE
LaunchPad Broken

### ISSUE THREAD

**Issue by RobLoach** [libretro/snes9x#22]
From https://github.com/libretro/snes9x/commit/03c8bad484ff5210c9a374d687d26126b6c1f71c ....

@sergiobenrocha2

> This "Verified" git stuff broke the launchpad code import... :/

@RobLoach

> https://help.github.com/articles/about-gpg-commit-and-tag-signatures/
> http://launchpadlibrarian.net/272633750/libretro-libretro-snes9x-libretro.log
> https://bugs.launchpad.net/ubuntu/+source/bzr-git/+bug/1084403

@fr500 

> It seems this is a long standing launchpad bug.
> The PPA is infact important I would advise to remove GPG signatures from
> commits to for the time being or at least provide a workaround

---

We should find a workaround, or another solution.

**Comment by sergiobenrocha2** [comment]
Just turn off this feature?

**Comment by RobLoach** [comment]
[Uploaded a patch](https://bugs.launchpad.net/ubuntu/+source/bzr-git/+bug/1084403/comments/39)

**Comment by i30817** [comment]
Since launchpad got support for mirror from github to their own git repositories (git support was made last month, fairly recent), it supports git extensions like gpgsig. I had to use launchpad git support for my own exult ppa when they switched from sourceforge svn to github (their github also uses gpgsig).

**Comment by sergiobenrocha2** [comment]
Launchpad does have git support, but does it have mirror support? You have to pull & push manually there as far as I know.

**Comment by RobLoach** [comment]
http://blog.launchpad.net/code/git-to-git-imports

Looks promising!

**Comment by sergiobenrocha2** [comment]
Launchpad has git mirroring now, you should fix this issue
