### ISSUE TITLE
MultiTap Not Recognized For Select Games

### ISSUE THREAD

**Issue by newoski** [libretro/snes9x#28]
I've tested all Multitap games using the snes9x core and all seem to work with the exception of:

**Looney Tunes B-Ball** -- The multiplayer options are grayed out, even with Multitap enabled 

**Virtual Soccer** - No multiplayer game options availble with Multitap enabled 

**Dino Dini's Soccer!** -- Multitap works on Genesis and I've read it's available for SNES but doesn't seem available on snes9x with Multitap enabled

Thanks

**Comment by newoski** [comment]
NHL 97 doesn't seem to work, either

**Comment by fr500** [comment]
This issue was moved to libretro/libretro-meta#4
