### ISSUE TITLE
Super back to the future ii (japan) with fastrom patch is not working

### ISSUE THREAD

**Issue by gabberhead** [libretro/snes9x#290]
i posted this also on the standalone snes9x gibthub site. this problem is already fixed for the standalone version, but not for the libretro core. here is the problem:

I tried the game with the fastrom patch from here:

https://www.romhacking.net/hacks/6607/

But the game is not starting in retroarch with the snes9x-current core. The screen goes black and stay this way. Without the fastrom patch the game is starting and running fine. Also with the english translation patch.

Then I tried the patched rom with the standalone version of snes9x on win11 and the the game is starting and running fine. Other older cores from snes9x core in retroarch I didn't tried it right now. But I will try it later.

here is the conversation about the problem:

https://github.com/snes9xgit/snes9x/issues/809

and here is the fix:

https://github.com/snes9xgit/snes9x/commit/a06974940362923c224626c6ecbcf0d96308d75e

**Comment by hizzlekizzle** [comment]
It'll get fixed whenever we sync up again with the upstream snes9x. In the meantime, you could build the libretro core from their upstream repo, which will already include the fix.

**Comment by gabberhead** [comment]
ok. thanx for the info. but i dont know how, because i never did it myself :) but it is also not importent. i can wait :)

**Comment by gabberhead** [comment]
testet and it works. thanx :)
i have a question. but its not telated to the fast rom issue. i try to load the english patched treasure conflix game. with the standalone verion of snes9x the game starts without problem. but with the libretro core, the game hangs at the now loading program,,, screen, after the game is started from within the house. the bios BS-X.bin is the english patched one, because i can not read japanese :) is this also an issue specific in the libretro core?
