### ISSUE TITLE
Super FX Black Screen

### ISSUE THREAD

**Issue by rtomasa** [libretro/snes9x#291]
Hi,

I'm developing a custom Libretro frontend, and I found out that Super FX games like StarFox start with black screen and no audio or video is displayed. Funny enough, DOOM is able to start and display the intro screen but after that it becomes black and unresponsive too.
Is there any undocumented parameter or something that need to be set for them to run from the frontend?

Sorry if this is not the proper place for these questions but I'm stuck with this.

**Comment by hizzlekizzle** [comment]
I don't know of anything special about the way SuperFX games function that would affect it at the API level. A quick skim of the libretro.cpp only brings up the SFX overclock setting. Perhaps that's getting set too high or something...?

**Comment by rtomasa** [comment]
I still do not have core config file implemented. I assumed that core was taking by default 100% on the SFX clock value. Is it possible that you require to set a specific value from the front-end to make it work?
