### ISSUE TITLE
(MSU-1) No audio when loading a save state

### ISSUE THREAD

**Issue by emarleau** [libretro/snes9x#30]
When you load a save state of a MSU-1 game there is no audio at all.

**Comment by qwertymodo** [comment]
Sorry about the dupe. See https://github.com/snes9xgit/snes9x/commit/0832528d9f4b0a9cc80d68df4b5d762be06e948e

**Comment by hizzlekizzle** [comment]
submitted a PR: https://github.com/libretro/snes9x/pull/36
