### ISSUE TITLE
(MSU-1) Crackling sound when using headphone

### ISSUE THREAD

**Issue by emarleau** [libretro/snes9x#31]
I'm not sure why but when I play a MSU-1 game with my headphones I hear a crackling sound from the right speaker. I'm not having this problem with standalone snes9x or even when I'm using my PC speaker. My guess is because my speakers are stereo and my headphone are 5.1 surround but I couldn't tell.

**Comment by emarleau** [comment]
It seems to be fixed with de latest nightly.

**Comment by hizzlekizzle** [comment]
eyyy, that's awesome! We pushed some MSU1-related stuff up but I wasn't sure how much--if any--good it did. Thanks for following up :)

**Comment by fr500** [comment]
This issue was moved to libretro/libretro-meta#13
