### ISSUE TITLE
Lufia II - Rise of the Sinistrals won't run if it has a nsrt header

### ISSUE THREAD

**Issue by i30817** [libretro/snes9x#34]
It's needed for some fan patches to softpatch.

output isn't anything different, except a eternal blackscreen. 'good' (without header) md5 is 
6efc477d6203ed2b3b9133c1cd9e9c5d

and with is
d35fcf90c273d4bc12eed59120954e58

For the purpose of testing, i renamed the ips patch so it wouldn't apply anyway. Needless to say, hanging headered roms is even worse than not presenting them on the playlist after a scan, which already happens.

**Comment by Alcaro** [comment]
Some IPS patches are for headered ROMs, and the IPS patch format doesn't have any way to tell whether it's intended for a headered or unheadered ROM. There's no way to fix this.

The only solution I can think of is switching to a more modern patch format, such as UPS or BPS.

**Comment by i30817** [comment]
The 'right' way to fix it is not to crash on a headered rom. You know, like upstream doesn't.

**Comment by hizzlekizzle** [comment]
apply patch to headered ROM > remove header from patched ROM > create new patch against unheadered ROM.

While you're at it, you can switch to a modern patch format that can tell the difference between headered and unheadered ROMs.

**Comment by i30817** [comment]
Should work as a workaround, thanks. I was thinking that would need more precaution to be a softpatch but it makes sense. But can i suggest for cores to not just hang if they happen to find a hardpatch or header they don't like? And suggesting a alternative would be good too.

**Comment by hizzlekizzle** [comment]
I agree that, soft-patching aside where there's nothing to be done about it as Alcaro said, accepting headered ROMs in general is definitely something we want to do. I can't speak for everyone involved but if it blackscreens with all headered ROMs right now, that's an oversight and we'll want to correct it.

**Comment by i30817** [comment]
Well, you can test it, all the info is in the first post. I tested it even without the ips patch active and it happened anyway.

**Comment by meepingsnesroms** [comment]
Unless it does this on Roms that haven't been patched this is a patch issue not a snes9x issue.

**Comment by i30817** [comment]
Uh, did you read the topic? YES it does it on roms that have not been patched. A header is not a patched, being essentially zeros.

**Comment by Alcaro** [comment]
If this core rejects all headered ROMs, and upstream doesn't, then that is indeed a bug that should be fixed. But then I must ask what softpatching has to do with anything.

If this core can softpatch unheadered ROMs only, and upstream can softpatch both, then upstream runs its softpatcher after removing NSRT headers. This can be fixed by either (1) moving softpatcher into the core (2) teaching RetroArch to remove said headers prior to softpatching (3) adding some kind of 'purify' function to cores.

1 would be a fair bit of code duplication and badly integrated with everything. 2 would be a direct violation of RetroArch's policies, it strongly resists awareness of any specific core. 3 feels like more effort than it's worth, softpatching is a fairly narrow usecase. But perhaps we should do 3 anyways.

**Comment by i30817** [comment]
Who said it rejected 'all headered ROMs'. I meant this one in particular. In fact, i tried in others and they worked. As for your conclusion that upstream removes headers i find that a bit strange, because the header is required for the (canonical, from the hacker) ips patches to work. Not all patches require it of course, but those that do state it on readmes.

**Comment by hizzlekizzle** [comment]
Ok, so most headered ROMs are fine, it's just *this* headered ROM? That's a very different problem from it rejecting *all* headered ROMs, which is what I thought you meant earlier. If it's just one game, it's going to be much harder for us to pin down, I think.

**Comment by i30817** [comment]
Yes it's for this headered rom. Test it out yourselves first, i've been bitten before by bad cfg configurations in retroarch (though i do not think this is the case here).

**Comment by i30817** [comment]
Oh, i forgot to tell it's the USA version, but i suppose you can tell from the md5.

**Comment by meepingsnesroms** [comment]
If the game is not patched and you have no IPS in the game directory does the original headered ROM work?

**Comment by i30817** [comment]
I will check again step for step, just for you to be sure:
1. copy paste headered rom to empty writable dir (so there is no confusion about srm files).
2. check its checksum: d35fcf90c273d4bc12eed59120954e58 (headered). Check with nsrt it is (it is).
3. run game with:
retroarch Lufia\ II\ -\ Rise\ of\ the\ Sinistrals\ \(USA\).sfc -L /usr/lib/x86_64-linux-gnu/libretro/snes9x_libretro.so 
Sound buffer size: 128160 (32040 samples)
Map_HiROMMap

(hang). 

Running the same game with snes9x from a ppa starts it just fine in less than a second.

**Comment by meepingsnesroms** [comment]
When I add an nsrt header to the unheadered rom(same checksum as yours before,used -addnsrt) my md5 checksum is fd4b8eea6b52ce3f26a7645353130e9f and it is also broke but works fine in bsnes and snes9x2010 so I will look into it.

Just use snes9x2010 for now.

Sorry for the disbelief,but the likeliness of it being the patch was so high I needed evidence.

**Comment by i30817** [comment]
Maybe nsrt changed its algorithm over the years. I used nsrt -addhead and nsrt -remhead btw. But if it happens to you too, doesn't matter.

**Comment by i30817** [comment]
Won't just removing the header prevent all ips patches that require a header from working? I mean it's your emulator, but i'd probably remove the ips patch support then because it'd be useless.

**Comment by Alcaro** [comment]
The NSRT header is not present on the emulated SNES, so it has to be removed at some point.

This specific point seems to be after the patch is applied, so headered patches will still work.

**Comment by meepingsnesroms** [comment]
The nsrt header is an outdated zsnes hack,the real snes doesn't have them.
RetroArch patches the ROM then loads it into a buffer and gives it to the emulator so the header is being removed after the ROM is patched so it should work fine now.

It is just doing what is described above with nsrt, converting the patched ROM to nonheadered format.

**Comment by fr500** [comment]
This issue was moved to libretro/libretro-meta#12
