### ISSUE TITLE
Needs game specific hack to display shadow in Air Strike Patrol.

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/snes9x#35]

**Comment by Alcaro** [comment]
Literally nothing except bsnes-accuracy emulates that, I'm not sure we need to worry about it. Especially considering upstream doesn't.

(I'd imagine emulating that specific register in a pixel-accurate way wouldn't be too complex...)

**Comment by meepingsnesroms** [comment]
`if(game == "ASP"){
    if(memory[INLEVEL]){
    framebufferdarkcircle(memory[PLANEX],memory[PLANEY] + offset)
    }
}`

**Comment by Alcaro** [comment]
good code

**Comment by meepingsnesroms** [comment]
I need to use the bsnes debugger to find the memory addresses listed but bsnes wont compile on my mac and complains about SecTrustSettings.h not having a valid uint32.

Does anyone have a precompiled bsnes or higan for mac os?

**Comment by meepingsnesroms** [comment]
Well got bsnes on linux then found out default bsnes has no debug features.
After getting bsnes debug for windows I found out sprite 0 is the top left of the player.
So now the code is:`if(game == "ASP"){ if(memory[INLEVEL] && brightnesstampered){ framebufferdarkcircle(sprite0Xcoord,currentline) } }`

Do you think that this would be accepted to the official repo when done?

**Comment by Alcaro** [comment]
I don't think this is the correct place to ask. Try [here](https://github.com/snes9xgit/snes9x/).

**Comment by fr500** [comment]
This issue was moved to libretro/libretro-meta#3
