### ISSUE TITLE
(Wii U) Can't fast forward if rewind enabled is on

### ISSUE THREAD

**Issue by MeisterLLD** [libretro/snes9x#39]
With last nightly (1.4.0) at the time of the post.
Fast forwarding works fine but if I go into settings > frame throttle (or something, sorry if I don't remember the name well) > enable rewind and put it ON, then fast forwarding doesn't work anymore. Rewind works fine though and is awesome !

Sorry if this is intended / to be expected

**Comment by fr500** [comment]
Most likely the WiiU is not fast enough to FF when rewind is enabled then

**Comment by MeisterLLD** [comment]
Seems strange, rewind just uses RAM whereas fast forward just uses more CPU no ? If I remember well both worked fine in Mame. I'll try to do a detailed list tomorrow.

**Comment by meepingsnesroms** [comment]
when you fast forward with rewind enabled it has to do more save states since if it savestates at every frame that would be 60 states per second,but if you do 2x fast forward now it has to save 120 states per second.(save states are very processor intensive because they have to backup the consoles entire address space)(so if a save state takes 1/10 second alone that is instant but times 120 is 12 seconds!)

**Comment by MeisterLLD** [comment]
You're right I didn't think of it that way !

**Comment by Alcaro** [comment]
Uh, what? The SNES has about 300KB memory in total. Yes, copying that takes a little time, and our savestate compressor also takes a bunch of microseconds, but that's completely insignificant compared to actually emulating the next frame.

Perhaps those extra microseconds is enough to push it over the 1/120s threshold, perhaps it's the frontend not liking that combination. But even if it's the former, fastforward framerate being throttled is a frontend bug. In neither case is there anything we can do here.

**Comment by MeisterLLD** [comment]
So wait I'm not sure to follow you Alcaro. Should I repost the issue in Retroarch ?

**Comment by MeisterLLD** [comment]
Just to say that it works in FB Alpha with games heavier than SNES roms like 1941 or SNK fighting games.

**Comment by fr500** [comment]
This issue was moved to libretro/libretro-meta#11
