### ISSUE TITLE
Black screen on Raspberry Pi 3 with Raspbian Jessie

### ISSUE THREAD

**Issue by joolswills** [libretro/snes9x#61]
Raspberry Pi 3 / Raspbian Jessie / armv7l / Kernel 4.9.35-v7+ / gcc 4.9.2

Launching a ROM gives a black screen. RetroArch is running, but nothing is rendered.

Building with `make -C libretro clean; make -C libretro platform=armvneon -j4`

Git Bisected to - 75ed73b2503698acb491e76e7e0dd888622c06f4

```
75ed73b2503698acb491e76e7e0dd888622c06f4 is the first bad commit
commit 75ed73b2503698acb491e76e7e0dd888622c06f4
Author: Sérgio Benjamim <sergio_br2@yahoo.com.br>
Date:   Wed Apr 26 22:44:25 2017 -0300

    Makefile cleanup

:040000 040000 ae3a901fbb34ac9df716439a93a83da6d877b37a 8d3b60147f360e22a0e68173480804cd86e8a140 M	libretro
```

**Comment by joolswills** [comment]
comparing the build log, looks as though -DARM is lost after this changeset along with `-marm -mfpu=neon` - those are less important as can be added by the caller (via CXXFLAGS), but -DARM is needed.

I just tested adding it back with 

```diff
diff --git a/libretro/Makefile b/libretro/Makefile
index 96b5737..caca63e 100644
--- a/libretro/Makefile
+++ b/libretro/Makefile
@@ -19,8 +19,10 @@ ifeq ($(platform),)
    endif
 else ifneq (,$(findstring armv,$(platform)))
    override platform += unix
+   CXXFLAGS += -DARM
 else ifneq (,$(findstring rpi,$(platform)))
    override platform += unix
+   CXXFLAGS += -DARM
 endif
 
 CXX                    ?= g++
```

and it works again - but I guess there should be an arm section lower down as there was before rather than setting the CXXFLAGS here - thoughts ?

**Comment by sergiobenrocha2** [comment]
You should put -DARM in other place, like this:

```
diff --git a/libretro/Makefile b/libretro/Makefile
index 2bedad2..9dba512 100644
--- a/libretro/Makefile
+++ b/libretro/Makefile
@@ -49,6 +49,14 @@ ifneq (,$(findstring unix,$(platform)))
       LIBS :=
    endif
 
+   # ARM
+   ifneq (,$(findstring armv,$(platform)))
+      CXXFLAGS += -DARM
+   # Raspberry Pi
+   else ifneq (,$(findstring rpi,$(platform)))
+      CXXFLAGS += -DARM
+   endif
+
 # OS X
 else ifeq ($(platform), osx)
    TARGET := $(TARGET_NAME)_libretro.dylib
```

**Comment by joolswills** [comment]
Are you going to do a PR for that or do you want me to? (as the arm section was removed in your PR).

**Comment by sergiobenrocha2** [comment]
No, I do it

**Comment by joolswills** [comment]
K. Thanks.

**Comment by hizzlekizzle** [comment]
Seems to be the same issue:
https://github.com/libretro/libretro-meta/issues/88
Let me know when this is fixed and I'l close out both.

**Comment by sergiobenrocha2** [comment]
I'm testing on my odroid board, got a black screen without -DARM too
