### ISSUE TITLE
Deae Tonosama Appare Ichiban - non working & weirdest error msg screen ever

### ISSUE THREAD

**Issue by nemo93** [libretro/snes9x#67]
**Deae Tonosama Appare Ichiban (Japan)**

=> this game does launch. However it goes straight to a very weird animated screen with an even weirder character and.. that's all. Pushing buttons does nothing. It does work with Snes9x1.53 & 1.54.1 Windows x64 (upstream), no weird screen to be seen here.

**Comment by Tatsuya79** [comment]
I can confirm this, that's a copy protection message.
I don't know why it's triggered with snes9x, the game is working with bsnes-mercury.

**Comment by kps501** [comment]
Even though game has no sram, memmap enables it anyway to zero bytes. Error doesn't happen in normal snes9x anytime (old builds). So I think libretro frontend maybe sometimes gets confused by this somewhere during S9xAppendMapping and re-enables it as non-battery backed ram.

Submitted a PR libretro-only hack that forcefully disables sram mapping if zero bytes. Should clear this issue from internal testing.

**Comment by Tatsuya79** [comment]
Thanks Deae Tonosama is booting fine now but we have other issues:
https://github.com/libretro/snes9x/issues/134

**Comment by kps501** [comment]
Double confirmed game works in https://buildbot.libretro.com/nightly and unrelated to #134. This can be safely closed.

**Comment by kps501** [comment]
Works in nightly for awhile. This can be closed if confirm okay.
https://buildbot.libretro.com/nightly/

**Comment by stellarporter** [comment]
Don't see any copy protection problems triggering with this game. #134 is closed too.
