### ISSUE TITLE
Request support for the newly translated "Tengai Makyou Zero: Far East of Eden"

### ISSUE THREAD

**Issue by KMFDManic** [libretro/snes9x#73]
The rom boots fine on the platform (NES Classic/SNES Classic) But, it can't pass the RTC test of the SPC7110.  This is definitely an inclusion that would make many people happy.  Thanks!

The snes cart has the SPC7110 chip that it is emulated by snes9x but its real time clock is not supported. Because of that RTC, the game is not passing the initial self test.

The code change for the working snes9x Windows version is here: 
http://www.mediafire.com/file/lxlf5dkj50mhlpq/CodeChangeTmz.rar

     ``<cartridge region="NTSC">
	<rom>
		<map mode='shadow' size='0x100000' address='00-0f:8000-ffff'/>
		<map mode='shadow' size='0x100000' address='80-bf:8000-ffff'/>
		<map mode='linear' size='0x100000' address='c0-cf:0000-ffff'/>
		<map mode='linear' offset='0x600000' address='40-4f:0000-ffff'/>
	</rom>
	<spc7110>
		<ram size='0x2000'>
			<map mode='linear' address='00:6000-7fff'/>
			<map mode='linear' address='30:6000-7fff'/>
		</ram>
		<mmio>
			<map address='00-3f:4800-483f'/>
			<map address='80-bf:4800-483f'/>
		</mmio>
		<mcu offset='0x100000'>
			<map address='d0-ff:0000-ffff' offset='0x100000' size='0x500000'/>
		</mcu>
		<dcu>
			<map address='50:0000-ffff'/>
		</dcu>
		<rtc>
			<map address='00-3f:4840-4842'/>
			<map address='80-bf:4840-4842'/>
		</rtc>
	</spc7110>
</cartridge>
 :+1: 1

**Comment by KMFDManic** [comment]
Because this would truly benefit MANY, upon several different formats, Android, 3DS, NESC/SNESC, etc, I put in a request (with your excellent info) to the great people who work on the 9x Core on a daily basis!  Thanks so much for pointing out this great game to me!  With the coding added, thousands will be able to enjoy the game:)  This is definitely something of interest to RPG Fans:)  Thanks again, and we should have things going within a few days!

**Comment by KMFDManic** [comment]
Thanks for getting this done!

**Comment by i30817** [comment]
Sorry to comment on a closed issue, but is this already working on the ppa? The game always fails on the self-test of the chip for me (asks to reboot), which i understand should be fixed.

I have the xml needed, named the same as the rom and ips patch (only with xml extension ofc).

**Comment by hizzlekizzle** [comment]
It should work fine. You do have to reset and do the hokey pokey while it creates the files it needs, but after resetting 2x, it should work.

**Comment by i30817** [comment]
Well, it always says 'the backup data isn't working', says everything is ok (if i reset twice, first time the RTC is wrong as you mention ). But it doesn't progress, either from reboot or quiting RA and reloading from cmd line.

The .rtc file is in the RA dir 'saves' dir along with the .srm as expected, but i keep the 'retroarch dir' somewhere else than might be expected with the emulator support for XDG_HOME.

Namely i do this:
`XDG_CONFIG_HOME=/media/i30817/Huggin/Documents/  retroarch -L /usr/l
ib/x86_64-linux-gnu/libretro/snes9x_libretro.so Tengai\ Makyou\ Zero\ \(Japan\).sfc `

Is it possible that you're reading the file wrong (since it obviously gets written?)

**Comment by hizzlekizzle** [comment]
I just tried it with softpatching (IPS) using the 4db0b95 build and it worked just fine in Windows. I can try it later in Linux.
