### ISSUE TITLE
[Request] Internal Resolution Core Option

### ISSUE THREAD

**Issue by Awakened0** [libretro/snes9x#76]
Currently the core automatically switches between outputting a 240 or 480 framebuffer depending on if a game is using high res mode or not. That should stay the default, but I think an option to always output 240 would be useful for shaders. The higan core lets you set the internal res to 240 and doesn't auto switch to 480 when high res stuff is onscreen in something like SD3. The high res text looks a little weird, but is still readable and I like how the rest of the image stays consistent with a CRT shader. There could be an option to always output 480 too, but I'm not sure if there is any benefit to doing that in SNES9x.

**Comment by hizzlekizzle** [comment]
I just put in a PR that adds an option to disable hires mode, which also disables interlaced mode. I think it should do what you're wanting. I can't actually find anything about hires blending in the source files, so I'm not really sure how to go about that one.

**Comment by Awakened0** [comment]
Thanks! Hmm, I didn't actually grab and run stand alone to see for myself (from googling, it looks like it still takes over file associations, which is annoying), but there are mentions of a "blend high-res images" option here: http://www.snes9x.com/phpbb3/viewtopic.php?f=6&t=5639

**Comment by Awakened0** [comment]
Doing a search on upstream's git, I find [this line](https://github.com/snes9xgit/snes9x/blob/09999378aca81d537415afa436b5157f9b08e26f/win32/win32_display.cpp#L749). But it's in win32_display.cpp, so maybe it's done in their frontend instead of the core :/

**Comment by Awakened0** [comment]
Tested it out with hires disabled. Secret of Mana's main menu is pretty illegible compared to higan with internal res set to 256x224. I wonder if backporting [this commit](https://github.com/snes9xgit/snes9x/commit/243ab9780657455a6f9f4be5499a69145cd6208f) would help with that.

**Comment by hizzlekizzle** [comment]
@Awakened0 
Can you try [this build (Win64)](https://www.mediafire.com/file/3bk868c63734y2i/snes9x_libretro.dll)? It didn't look any better in my limited testing, but I thought you might want to give it a shot.

**Comment by Awakened0** [comment]
Yeah, it looks identical to the buildbot build, at least on the SoM New Game or Game File screen. Maybe maister's method of downscaling hires is just really good in the higan core. The text looks really good with the blur option off.

**Comment by Awakened0** [comment]
Anyways, the hires text in SD3 is still readable with hires off, which is really where I wanted to turn it off since it switches modes during gameplay. I don't mind using a game option override to enable hires for SoM, since it only uses it in menus. I'd still like a blending option if possible, but I have the other issue open for that, so I'll close this one.
