### ISSUE TITLE
Super Metroid graphics error

### ISSUE THREAD

**Issue by 1985a** [libretro/snes9x#78]
In Super Metroid on Tourian Map, specifically, in mother brain attempt If you load the "VAR" beam, then release the secret weapon you will see an error that I don't see and another one, example {higan} or SNES real console.

Here a few images.
[0](https://i.imgur.com/ikIzMt4.png)
[1](https://i.imgur.com/PbcnLiF.png)
[2](https://i.imgur.com/hDbX7mg.png)
[3](https://i.imgur.com/RmPRT9H.png)

Finally, expected behavior, like on real snes
[4](https://i.imgur.com/Q6SWabM.png)

BTW, my English is not my mother language if you see any mistake.

**Comment by hizzlekizzle** [comment]
Can you see if you get the same behavior in snes9x standalone?

**Comment by 1985a** [comment]
Yes, it does.

**Comment by 1985a** [comment]
BTW, I forget to put the savegame here
[save](http://www43.zippyshare.com/v/MVVcyjlB/file.html)

[video](http://www43.zippyshare.com/v/pOr6xWDC/file.html)

**Comment by nikkoman** [comment]
Is this still an issue on 6f1be93 ?

**Comment by kps501** [comment]
Murder Beam is snes9x retroarch fixed as of idk. Tested using latest build and shows real hardware picture. Can close this.
