### ISSUE TITLE
[WiiU] Frequent "System Memory Error 160-2203" when reloading core

### ISSUE THREAD

**Issue by gblues** [libretro/snes9x#88]
I've been running into System Memory Errors very frequently in my work on RetroArch; and I've been driving myself nuts trying to figure it out. However, I've isolated the problem to this core.

There's some magic that happens when switching cores on WiiU. I don't fully understand it, but based on a discord convo with @aliaspider, it seems like the SME can occur if certain sensitive bits of memory are written to by mistake, causing the loader to feed invalid data to the RPX loader which, in turn, sets off the OS' "bad executable" handler (the 160-2203 message).

How did I Isolate it to this core?
---
Lots and lots of testing.

The reproduction process looks like this:

1. Put together a set of 10 SNES games and 10 NES games.
2. Build the nestopia core, snes9x core, and snes9x2005 core.
3. To speed things up for yourself, create 3 playlists:
    * 1 that maps the SNES games to the snes9x_libretro.rpx core
    * 1 that maps the SNES games to the snes9x2005_libretro.rpx core
    * 1 that maps the NES games to the nestopia_libretro.rpx core
4. Load up RetroArch and alternate between loading NES and SNES9x2005 games. You should be able to get through all 20 games no problem.
5. Repeat the process, but instead alternate between snes9x and nestopia.

It tends to vary, but I usually end up getting the System Memory Error within 5-6 switches (i.e. maybe 2 or 3 SNES games).

I've done this same stress-test using nestopia, snes9x2005, and mednafen_ngp cores with no issues.

snes9x has always been crashy on WiiU, so I don't know if there even is a point in time where it didn't crash.

**Comment by aliaspider** [comment]
what is the size of the rpx files?

**Comment by gblues** [comment]
mednafen_ngp_libretro.rpx    4,272kb
    nestopia_libretro.rpx        5,617kb
    snes9x_libretro.rpx          6,375kb
    snes9x2005_libretro.rpx      4,650kb

**Comment by aliaspider** [comment]
yeah as I suspected, snes9x is bigger than the others that is why it is hit by the memory corruption while loading. I assume any core of that size or bigger will trigger the memory error.
